# Generated by Django 5.1.3 on 2024-12-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
