# Generated by Django 5.1.3 on 2024-12-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_additional_notes_ticket_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Client',
        ),
    ]
