# Generated by Django 5.1.3 on 2024-12-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_ticket_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
    ]
